### ISSUE TITLE
Please remove Bluebird dependency

### ISSUE THREAD

**Issue by alexgorbatchev** [types/npm-rethinkdb#1]
I think Bluebird dependency needs to be removed as this makes the whole rethinkdb incompatible with ES6 `Promise` object. Bluebird is used by rethinkdb behind the scenes, what gets exposed are ES6 promises.

```
tests/index-test.ts (12,12): Type 'Bluebird<ArrayResult<string>>' is not assignable to type 'Promise<ArrayResult<string>>'.
```

**Comment by blakeembrey** [comment]
What gets exposed is still Bluebird, so I won't be removing it. You can check the issues on Bluebird for the patch to this, which has already landed and the dependency just needs to be updated.

**Comment by alexgorbatchev** [comment]
For reference: https://github.com/types/npm-bluebird/commit/ba2d13996110473d45df387850d276c1a32a383a and https://github.com/types/npm-bluebird/commit/ca3bb021ce522fd0498496b4048786de072ae7d3

Sounds good. When do you expect to publish this?

**Comment by blakeembrey** [comment]
@alexgorbatchev When I'm free. I hadn't run into these issues personally, but it's a trivial update for a PR.

**Comment by blakeembrey** [comment]
Done. You can install from GitHub for now, or submit a PR to the registry. I still have a few more improvements I was hoping to make on the RethinkDB definition - mostly around `literal()` support that I run into.

**Comment by blakeembrey** [comment]
@alexgorbatchev I assume you're using 2.0, right? I just realised the "fix" breaks everyone else including the tests in this repo 😢 As a workaround, I'd consider going 2.0 only for this definition.

**Comment by felixfbecker** [comment]
@blakeembrey we should test against multiple TS versions on Travis

**Comment by felixfbecker** [comment]
All repos in general

**Comment by blakeembrey** [comment]
Yes, I agree. Need to make setup easier.
