### ISSUE TITLE
Adopt rethinkdbdash definitions

### ISSUE THREAD

**Issue by marshall007** [types/npm-rethinkdb#11]
@blakeembrey I think I have finally accomplished what you were getting at in our previous discussion (#8). I have the repo up here: https://github.com/marshall007/npm-rethinkdbdash.

Apologies again for copying the definitions into that DefinitelyTyped PR, I just didn't understand enough about how all this works at the time to appreciate what the goals are here.

@blakeembrey @niieani I hope you guys will consider migrating my repo to the @types org and publish them to NPM.

Cheers!

**Comment by blakeembrey** [comment]
Nice work! You're welcome to move the repo to @types. Let me know add you so you can move it 😄

**Comment by marshall007** [comment]
@blakeembrey ok sounds good, yea I'm happy to move it over.

**Comment by marshall007** [comment]
@blakeembrey I have transferred the repo: https://github.com/types/npm-rethinkdbdash

Can you walk me through the next steps? I don't think I have the ability to enable travis or greenkeeper per the [guidelines](https://github.com/types/guidelines#quickly-enable-travis-ci-and-greenkeeper). I imagine we'll also need a PR to the registry repo as well?

**Comment by unional** [comment]
I'll rename the repo to `types/rethinkdbdash`?

Yes, a PR to registry. But let's get the travis up first.

**Comment by blakeembrey** [comment]
> I imagine we'll also need a PR to the registry repo as well?

Yep, that would be great.

@unional We can definitely start doing that overall. This is related to a greater discussion for all @types though to align with NPM `@types`. I'm happy to do that, I'll just need to move the guidelines to @typings for now and update the guidelines going forward.
