### ISSUE TITLE
merge operator on RTableSlice

### ISSUE THREAD

**Issue by ktersius** [types/npm-rethinkdb#5]
Seems that the merge operator is missing on RTableSlice<T> ?
For example this query is valid.

```
r.db('devDB')
.table('RoleMapping')
.filter({"principalId": 'fd079f60-adf0-4470-af08-df074774703c', principalType: 'USER'})
.merge(roleMapping => {
                return r.db('devDB').table("Role").filter({"id": roleMapping("roleId")}).nth(0).pluck("name", "id");
            })
.pluck("name", "id");

```

**Comment by blakeembrey** [comment]
Thanks, I just added it to `RTableSlice`. Since there's a lot of duplication going on to support the correct types, it's likely a few things have been missed.
