### ISSUE TITLE
Property 'eqJoin' does not exist on type 'RTable<{}>'

### ISSUE THREAD

**Issue by sanderpick** [types/npm-rethinkdb#7]
![screen shot 2016-12-07 at 9 40 55 am](https://cloud.githubusercontent.com/assets/361000/20979320/538ee096-bc61-11e6-81dc-4e875312ae28.png)

This runs fine, but compiler complains.

**Comment by unional** [comment]
FYI, TypeScript is non-intrusive. Even if the compilation failed with type checks, it will still emit JavaScript file as if it is ok. That's why it runs fine but the compiler complains. 🌷

**Comment by sanderpick** [comment]
kickass @blakeembrey thanks. @unional, no doubt.
