### ISSUE TITLE
Property 'contains' does not exist on type 'RArray<string>'

### ISSUE THREAD

**Issue by lukeify** [types/npm-rethinkdb#9]
Typescript Error TS2339. Produced with this code:

```Typescript
    let result  = await r.dbList().contains(config.dbName).do(databaseExists => {
                    return r.branch(databaseExists, { dbs_created: 0 }, r.dbCreate(config.dbName));
                }).run(conn);
```

It's complaining `.contains()` is not available off of `.dbList()`. 

Should this be valid considering the code itself works and [has been mentioned here](https://github.com/rethinkdb/rethinkdb/issues/3512)?

**Comment by blakeembrey** [comment]
Feel free to submit a PR, it just need to be added to https://github.com/types/npm-rethinkdb/blob/3cc3da29b0b54eb522d0843034ca5a9ade796ea8/rethinkdb.d.ts#L31.

**Comment by lukeify** [comment]
Closing as per #10
